name = "controle-de-improprio"
main = "index.js"
compatibility_date = "2026-01-01"

[vars]
# Podes definir as tuas chaves aqui ou diretamente no painel da Cloudflare (em Settings > Variables)
# TMDB_KEY = "a_tua_chave_tmdb"
# MDBLIST_KEY = "a_tua_chave_mdblist"
# BLOQUEAR_SEM_CLASSIFICACAO = "0"